  - name: Install dependencies
    tags: always
    become: yes
    apt: 
      name: ['apt-transport-https', 'build-essential', 'ca-certificates', 'curl', 'git', 'python3-dev', 'python3-pip', 'virtualenv','python3-setuptools', 'software-properties-common', 'unzip', 'vim', 'erlang','aptitude']
      state: latest
      install_recommends: no
      update_cache: yes

  # - name: Install aptitude using apt
  #   apt:
  #     name: ['aptitude']
  #     state: latest
  #     update_cache: yes
  #     force_apt_get: yes

    # - name: Install required system packages
    # apt:
    #   name: ['{{ item }}']
    #   state: latest
    #   update_cache: yes
    # loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']